version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - ECR_PREFIX="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_PREFIX
      - echo "Building 6 images for marketplace deployment..."

  build:
    commands:
      - echo Build started on `date`

      # Build API (FastAPI backend)
      - echo "Building API..."
      - docker build -f Dockerfile.api -t $ECR_PREFIX/marketplace-api:latest -t $ECR_PREFIX/marketplace-api:$CODEBUILD_RESOLVED_SOURCE_VERSION .

      # Build MCP Server (marketplace version)
      - echo "Building MCP Server..."
      - docker build -f Dockerfile -t $ECR_PREFIX/marketplace-mcp:latest -t $ECR_PREFIX/marketplace-mcp:$CODEBUILD_RESOLVED_SOURCE_VERSION .

      # Build Celery Worker
      - echo "Building Celery Worker..."
      - docker build -f Dockerfile.worker -t $ECR_PREFIX/marketplace-worker:latest -t $ECR_PREFIX/marketplace-worker:$CODEBUILD_RESOLVED_SOURCE_VERSION .

      # Build Debate UI
      - echo "Building Debate UI..."
      - cd persona-debate-ui
      - docker build -f Dockerfile -t $ECR_PREFIX/marketplace-debate-ui:latest -t $ECR_PREFIX/marketplace-debate-ui:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - cd ..

      # Build Admin UI
      - echo "Building Admin UI..."
      - cd admin-ui
      - docker build -f Dockerfile -t $ECR_PREFIX/marketplace-admin-ui:latest -t $ECR_PREFIX/marketplace-admin-ui:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - cd ..

      # Pull Redis from Docker Hub
      - echo "Pulling Redis..."
      - docker pull redis:7-alpine
      - docker tag redis:7-alpine $ECR_PREFIX/marketplace-redis:latest
      - docker tag redis:7-alpine $ECR_PREFIX/marketplace-redis:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo Pushing Docker images to ECR...

      # Push API
      - docker push $ECR_PREFIX/marketplace-api:latest
      - docker push $ECR_PREFIX/marketplace-api:$CODEBUILD_RESOLVED_SOURCE_VERSION

      # Push MCP Server
      - docker push $ECR_PREFIX/marketplace-mcp:latest
      - docker push $ECR_PREFIX/marketplace-mcp:$CODEBUILD_RESOLVED_SOURCE_VERSION

      # Push Worker
      - docker push $ECR_PREFIX/marketplace-worker:latest
      - docker push $ECR_PREFIX/marketplace-worker:$CODEBUILD_RESOLVED_SOURCE_VERSION

      # Push Debate UI
      - docker push $ECR_PREFIX/marketplace-debate-ui:latest
      - docker push $ECR_PREFIX/marketplace-debate-ui:$CODEBUILD_RESOLVED_SOURCE_VERSION

      # Push Admin UI
      - docker push $ECR_PREFIX/marketplace-admin-ui:latest
      - docker push $ECR_PREFIX/marketplace-admin-ui:$CODEBUILD_RESOLVED_SOURCE_VERSION

      # Push Redis
      - docker push $ECR_PREFIX/marketplace-redis:latest
      - docker push $ECR_PREFIX/marketplace-redis:$CODEBUILD_RESOLVED_SOURCE_VERSION

      - echo Build completed on `date`
      - echo "Successfully pushed 6 MARKETPLACE images to ECR"
      - echo "Images:"
      - echo "  - $ECR_PREFIX/marketplace-api:latest"
      - echo "  - $ECR_PREFIX/marketplace-mcp:latest"
      - echo "  - $ECR_PREFIX/marketplace-worker:latest"
      - echo "  - $ECR_PREFIX/marketplace-debate-ui:latest"
      - echo "  - $ECR_PREFIX/marketplace-admin-ui:latest"
      - echo "  - $ECR_PREFIX/marketplace-redis:latest"

artifacts:
  files:
    - '**/*'
